// Auto-generated by update_csat_board.sh — do not edit manually
// Last updated: 2026-05-07T18:03:04Z

const CSAT_DATA = {
  "generatedAt": "2026-05-07T18:03:04Z",
  "weekLabel": "Week of May 4 \u2013 May 8",
  "quarterStart": "2026-04-01",
  "teams": [
    {
      "id": "norma",
      "name": "Team Norma",
      "manager": "Norma Ruy Sanchez",
      "color": "#9B59D0",
      "totalPoints": 5
    },
    {
      "id": "pablo",
      "name": "Team Pablo",
      "manager": "Pablo Acosta",
      "color": "#E07832",
      "totalPoints": 17
    }
  ],
  "players": [
    {
      "name": "Alejandro Nunez",
      "email": "alejandro.nunezpriego@datadoghq.com",
      "initials": "AN",
      "color": "#9B59D0",
      "team": "norma",
      "csatWithComment": 1,
      "csatNoComment": 1,
      "totalGoodCsat": 2,
      "totalBadCsat": 0,
      "totalPoints": 3
    },
    {
      "name": "Diego Corrales",
      "email": "diego.corrales@datadoghq.com",
      "initials": "DC",
      "color": "#E07832",
      "team": "norma",
      "csatWithComment": 0,
      "csatNoComment": 0,
      "totalGoodCsat": 0,
      "totalBadCsat": 0,
      "totalPoints": 0
    },
    {
      "name": "Patrizio Storms",
      "email": "patrizio.storms@datadoghq.com",
      "initials": "PS",
      "color": "#5282E0",
      "team": "norma",
      "csatWithComment": 0,
      "csatNoComment": 0,
      "totalGoodCsat": 0,
      "totalBadCsat": 0,
      "totalPoints": 0
    },
    {
      "name": "Emmanuel Prieto",
      "email": "emmanuel.prieto@datadoghq.com",
      "initials": "EP",
      "color": "#52C87A",
      "team": "norma",
      "csatWithComment": 0,
      "csatNoComment": 1,
      "totalGoodCsat": 1,
      "totalBadCsat": 0,
      "totalPoints": 1
    },
    {
      "name": "Emanuel Baltazar",
      "email": "emanuel.carmona@datadoghq.com",
      "initials": "EB",
      "color": "#E0C452",
      "team": "norma",
      "csatWithComment": 0,
      "csatNoComment": 0,
      "totalGoodCsat": 0,
      "totalBadCsat": 0,
      "totalPoints": 0
    },
    {
      "name": "Jonathan Maya",
      "email": "jonathan.maya@datadoghq.com",
      "initials": "JM",
      "color": "#E05252",
      "team": "norma",
      "csatWithComment": 0,
      "csatNoComment": 1,
      "totalGoodCsat": 1,
      "totalBadCsat": 0,
      "totalPoints": 1
    },
    {
      "name": "Jaime Becerril",
      "email": "jaime.becerril@datadoghq.com",
      "initials": "JB",
      "color": "#58D9C8",
      "team": "pablo",
      "csatWithComment": 3,
      "csatNoComment": 0,
      "totalGoodCsat": 3,
      "totalBadCsat": 0,
      "totalPoints": 6
    },
    {
      "name": "Israel Lopez",
      "email": "israel.lopez@datadoghq.com",
      "initials": "IL",
      "color": "#D958A6",
      "team": "pablo",
      "csatWithComment": 0,
      "csatNoComment": 0,
      "totalGoodCsat": 0,
      "totalBadCsat": 0,
      "totalPoints": 0
    },
    {
      "name": "Alberto Bautista",
      "email": "alberto.bautista@datadoghq.com",
      "initials": "AB",
      "color": "#8ED952",
      "team": "pablo",
      "csatWithComment": 1,
      "csatNoComment": 1,
      "totalGoodCsat": 2,
      "totalBadCsat": 0,
      "totalPoints": 3
    },
    {
      "name": "Marco Perez",
      "email": "marco.perez@datadoghq.com",
      "initials": "MP",
      "color": "#52A6E0",
      "team": "pablo",
      "csatWithComment": 1,
      "csatNoComment": 1,
      "totalGoodCsat": 2,
      "totalBadCsat": 0,
      "totalPoints": 3
    },
    {
      "name": "Fernanda Ramirez",
      "email": "fernanda.ramirez@datadoghq.com",
      "initials": "FR",
      "color": "#E08052",
      "team": "pablo",
      "csatWithComment": 0,
      "csatNoComment": 0,
      "totalGoodCsat": 0,
      "totalBadCsat": 0,
      "totalPoints": 0
    },
    {
      "name": "Cesar Medrano",
      "email": "cesar.medrano@datadoghq.com",
      "initials": "CM",
      "color": "#A652E0",
      "team": "pablo",
      "csatWithComment": 1,
      "csatNoComment": 0,
      "totalGoodCsat": 1,
      "totalBadCsat": 0,
      "totalPoints": 2
    },
    {
      "name": "Eric Torres",
      "email": "eric.torres@datadoghq.com",
      "initials": "ET",
      "color": "#52E0A6",
      "team": "pablo",
      "csatWithComment": 1,
      "csatNoComment": 1,
      "totalGoodCsat": 2,
      "totalBadCsat": 0,
      "totalPoints": 3
    }
  ],
  "csatHistory": [
    {
      "name": "Eric Torres",
      "initials": "ET",
      "color": "#52E0A6",
      "team": "pablo",
      "ticketId": 2889806,
      "comment": "",
      "hasComment": false,
      "points": 1,
      "date": "2026-05-07",
      "niceDate": "May 7"
    },
    {
      "name": "Eric Torres",
      "initials": "ET",
      "color": "#52E0A6",
      "team": "pablo",
      "ticketId": 2889781,
      "comment": "Eric was very knowledgable and quick to identify my issue.  He even took the time to find the AWS documentation for me that would be useful in my situation.  A+",
      "hasComment": true,
      "points": 2,
      "date": "2026-05-07",
      "niceDate": "May 7"
    },
    {
      "name": "Jaime Becerril",
      "initials": "JB",
      "color": "#58D9C8",
      "team": "pablo",
      "ticketId": 2889178,
      "comment": "Wow! I'm on the other side now!",
      "hasComment": true,
      "points": 2,
      "date": "2026-05-06",
      "niceDate": "May 6"
    },
    {
      "name": "Jaime Becerril",
      "initials": "JB",
      "color": "#58D9C8",
      "team": "pablo",
      "ticketId": 2889171,
      "comment": "quick response",
      "hasComment": true,
      "points": 2,
      "date": "2026-05-06",
      "niceDate": "May 6"
    },
    {
      "name": "Jaime Becerril",
      "initials": "JB",
      "color": "#58D9C8",
      "team": "pablo",
      "ticketId": 2889133,
      "comment": "got solution to my query in very quick time",
      "hasComment": true,
      "points": 2,
      "date": "2026-05-06",
      "niceDate": "May 6"
    },
    {
      "name": "Alberto Bautista",
      "initials": "AB",
      "color": "#8ED952",
      "team": "pablo",
      "ticketId": 2889120,
      "comment": "",
      "hasComment": false,
      "points": 1,
      "date": "2026-05-06",
      "niceDate": "May 6"
    },
    {
      "name": "Marco Perez",
      "initials": "MP",
      "color": "#52A6E0",
      "team": "pablo",
      "ticketId": 2889093,
      "comment": "Marco is PHENOMENAL",
      "hasComment": true,
      "points": 2,
      "date": "2026-05-06",
      "niceDate": "May 6"
    },
    {
      "name": "Emmanuel Prieto",
      "initials": "EP",
      "color": "#52C87A",
      "team": "norma",
      "ticketId": 2889072,
      "comment": "",
      "hasComment": false,
      "points": 1,
      "date": "2026-05-06",
      "niceDate": "May 6"
    },
    {
      "name": "Marco Perez",
      "initials": "MP",
      "color": "#52A6E0",
      "team": "pablo",
      "ticketId": 2887622,
      "comment": "",
      "hasComment": false,
      "points": 1,
      "date": "2026-05-05",
      "niceDate": "May 5"
    },
    {
      "name": "Jonathan Maya",
      "initials": "JM",
      "color": "#E05252",
      "team": "norma",
      "ticketId": 2887212,
      "comment": "",
      "hasComment": false,
      "points": 1,
      "date": "2026-05-05",
      "niceDate": "May 5"
    },
    {
      "name": "Alberto Bautista",
      "initials": "AB",
      "color": "#8ED952",
      "team": "pablo",
      "ticketId": 2879610,
      "comment": "Success!",
      "hasComment": true,
      "points": 2,
      "date": "2026-05-05",
      "niceDate": "May 5"
    },
    {
      "name": "Cesar Medrano",
      "initials": "CM",
      "color": "#A652E0",
      "team": "pablo",
      "ticketId": 2880696,
      "comment": "thank you. right to the point",
      "hasComment": true,
      "points": 2,
      "date": "2026-05-05",
      "niceDate": "May 5"
    },
    {
      "name": "Alejandro Nunez",
      "initials": "AN",
      "color": "#9B59D0",
      "team": "norma",
      "ticketId": 2870051,
      "comment": "",
      "hasComment": false,
      "points": 1,
      "date": "2026-05-05",
      "niceDate": "May 5"
    },
    {
      "name": "Alejandro Nunez",
      "initials": "AN",
      "color": "#9B59D0",
      "team": "norma",
      "ticketId": 2886417,
      "comment": "Correct, complete, and fast. Great!",
      "hasComment": true,
      "points": 2,
      "date": "2026-05-05",
      "niceDate": "May 5"
    }
  ]
};
