// Auto-generated by update_csat_board.sh — do not edit manually
// Last updated: 2026-05-06T19:33:46Z

const CSAT_DATA = {
  "generatedAt": "2026-05-06T19:33:46Z",
  "weekLabel": "Week of May 4 \u2013 May 8",
  "quarterStart": "2026-04-01",
  "teams": [
    {
      "id": "norma",
      "name": "Team Norma",
      "manager": "Norma Ruy Sanchez",
      "color": "#9B59D0",
      "totalPoints": 31
    },
    {
      "id": "pablo",
      "name": "Team Pablo",
      "manager": "Pablo Acosta",
      "color": "#E07832",
      "totalPoints": 35
    }
  ],
  "players": [
    {
      "name": "Alejandro Nunez",
      "email": "alejandro.nunezpriego@datadoghq.com",
      "initials": "AN",
      "color": "#9B59D0",
      "team": "norma",
      "csatWithComment": 4,
      "csatNoComment": 2,
      "totalGoodCsat": 6,
      "totalBadCsat": 1,
      "totalPoints": 10
    },
    {
      "name": "Diego Corrales",
      "email": "diego.corrales@datadoghq.com",
      "initials": "DC",
      "color": "#E07832",
      "team": "norma",
      "csatWithComment": 2,
      "csatNoComment": 0,
      "totalGoodCsat": 2,
      "totalBadCsat": 0,
      "totalPoints": 4
    },
    {
      "name": "Patrizio Storms",
      "email": "patrizio.storms@datadoghq.com",
      "initials": "PS",
      "color": "#5282E0",
      "team": "norma",
      "csatWithComment": 1,
      "csatNoComment": 3,
      "totalGoodCsat": 4,
      "totalBadCsat": 0,
      "totalPoints": 5
    },
    {
      "name": "Emmanuel Prieto",
      "email": "emmanuel.prieto@datadoghq.com",
      "initials": "EP",
      "color": "#52C87A",
      "team": "norma",
      "csatWithComment": 0,
      "csatNoComment": 4,
      "totalGoodCsat": 4,
      "totalBadCsat": 0,
      "totalPoints": 4
    },
    {
      "name": "Emanuel Baltazar",
      "email": "emanuel.carmona@datadoghq.com",
      "initials": "EB",
      "color": "#E0C452",
      "team": "norma",
      "csatWithComment": 0,
      "csatNoComment": 3,
      "totalGoodCsat": 3,
      "totalBadCsat": 0,
      "totalPoints": 3
    },
    {
      "name": "Jonathan Maya",
      "email": "jonathan.maya@datadoghq.com",
      "initials": "JM",
      "color": "#E05252",
      "team": "norma",
      "csatWithComment": 1,
      "csatNoComment": 3,
      "totalGoodCsat": 4,
      "totalBadCsat": 0,
      "totalPoints": 5
    },
    {
      "name": "Jaime Becerril",
      "email": "jaime.becerril@datadoghq.com",
      "initials": "JB",
      "color": "#58D9C8",
      "team": "pablo",
      "csatWithComment": 5,
      "csatNoComment": 0,
      "totalGoodCsat": 5,
      "totalBadCsat": 0,
      "totalPoints": 10
    },
    {
      "name": "Israel Lopez",
      "email": "israel.lopez@datadoghq.com",
      "initials": "IL",
      "color": "#D958A6",
      "team": "pablo",
      "csatWithComment": 1,
      "csatNoComment": 1,
      "totalGoodCsat": 2,
      "totalBadCsat": 1,
      "totalPoints": 3
    },
    {
      "name": "Alberto Bautista",
      "email": "alberto.bautista@datadoghq.com",
      "initials": "AB",
      "color": "#8ED952",
      "team": "pablo",
      "csatWithComment": 1,
      "csatNoComment": 1,
      "totalGoodCsat": 2,
      "totalBadCsat": 0,
      "totalPoints": 3
    },
    {
      "name": "Marco Perez",
      "email": "marco.perez@datadoghq.com",
      "initials": "MP",
      "color": "#52A6E0",
      "team": "pablo",
      "csatWithComment": 2,
      "csatNoComment": 4,
      "totalGoodCsat": 6,
      "totalBadCsat": 0,
      "totalPoints": 8
    },
    {
      "name": "Fernanda Ramirez",
      "email": "fernanda.ramirez@datadoghq.com",
      "initials": "FR",
      "color": "#E08052",
      "team": "pablo",
      "csatWithComment": 0,
      "csatNoComment": 0,
      "totalGoodCsat": 0,
      "totalBadCsat": 0,
      "totalPoints": 0
    },
    {
      "name": "Cesar Medrano",
      "email": "cesar.medrano@datadoghq.com",
      "initials": "CM",
      "color": "#A652E0",
      "team": "pablo",
      "csatWithComment": 2,
      "csatNoComment": 1,
      "totalGoodCsat": 3,
      "totalBadCsat": 0,
      "totalPoints": 5
    },
    {
      "name": "Eric Torres",
      "email": "eric.torres@datadoghq.com",
      "initials": "ET",
      "color": "#52E0A6",
      "team": "pablo",
      "csatWithComment": 1,
      "csatNoComment": 4,
      "totalGoodCsat": 5,
      "totalBadCsat": 0,
      "totalPoints": 6
    }
  ]
};
