// Auto-generated by update_csat_board.sh — do not edit manually
// Last updated: (not yet run)

const CSAT_DATA = {
  "generatedAt": null,
  "weekLabel": "—",
  "quarterStart": "2026-04-01",
  "teams": [
    {
      "id": "norma",
      "name": "Team Norma",
      "manager": "Norma Ruy Sanchez",
      "color": "#632CA6",
      "totalPoints": 0,
      "members": []
    },
    {
      "id": "pablo",
      "name": "Team Pablo",
      "manager": "Pablo Acosta",
      "color": "#E07832",
      "totalPoints": 0,
      "members": []
    }
  ],
  "players": []
};
